/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedContasAPagarRouteImport } from './routes/_authenticated.contas-a-pagar'
import { Route as AuthenticatedContasAReceberRouteImport } from './routes/_authenticated.contas-a-receber'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContasAPagarRoute =
  AuthenticatedContasAPagarRouteImport.update({
    id: '/contas-a-pagar',
    path: '/contas-a-pagar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContasAReceberRoute =
  AuthenticatedContasAReceberRouteImport.update({
    id: '/contas-a-receber',
    path: '/contas-a-receber',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/contas-a-pagar': typeof AuthenticatedContasAPagarRoute
  '/contas-a-receber': typeof AuthenticatedContasAReceberRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/contas-a-pagar': typeof AuthenticatedContasAPagarRoute
  '/contas-a-receber': typeof AuthenticatedContasAReceberRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/contas-a-pagar': typeof AuthenticatedContasAPagarRoute
  '/_authenticated/contas-a-receber': typeof AuthenticatedContasAReceberRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/contas-a-pagar' | '/contas-a-receber'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/contas-a-pagar' | '/contas-a-receber' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/contas-a-pagar'
    | '/_authenticated/contas-a-receber'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contas-a-pagar': {
      id: '/_authenticated/contas-a-pagar'
      path: '/contas-a-pagar'
      fullPath: '/contas-a-pagar'
      preLoaderRoute: typeof AuthenticatedContasAPagarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contas-a-receber': {
      id: '/_authenticated/contas-a-receber'
      path: '/contas-a-receber'
      fullPath: '/contas-a-receber'
      preLoaderRoute: typeof AuthenticatedContasAReceberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedContasAPagarRoute: typeof AuthenticatedContasAPagarRoute
  AuthenticatedContasAReceberRoute: typeof AuthenticatedContasAReceberRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedContasAPagarRoute: AuthenticatedContasAPagarRoute,
  AuthenticatedContasAReceberRoute: AuthenticatedContasAReceberRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
